name: tests

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    tests:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: true
            matrix:
                os: [ ubuntu-latest ]
                php: [ 8.4, 8.3, 8.2, 8.1 ]
                laravel: [ 12.*, 11.*, 10.*, 9.* ]
                stability: [ prefer-lowest, prefer-stable ]
                include:
                    -   laravel: 12.*
                        testbench: 10.*
                        carbon: ^3.8.4
                        twilio: ^4.1.0
                    -   laravel: 11.*
                        testbench: 9.*
                        carbon: ^2.63
                        twilio: ^4.1.0
                    -   laravel: 10.*
                        testbench: 8.*
                        carbon: ^2.63
                        twilio: ^3.4
                    -   laravel: 9.*
                        testbench: 7.*
                        carbon: ^2.63
                        twilio: ^3.4
                exclude:
                    -   laravel: 12.*
                        php: 8.1
                    -   laravel: 11.*
                        php: 8.1

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Install SQLite 3
                run: |
                    sudo apt-get update
                    sudo apt-get install sqlite3 -y

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
                    coverage: none\

            -   name: Install dependencies
                run: |
                    composer require "dash8x/dhiraagu-sms-notification" "laravel-notification-channels/twilio:${{ matrix.twilio }}" "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "nesbot/carbon:${{ matrix.carbon }}" --no-interaction --no-update
                    composer update --${{ matrix.stability }} --prefer-dist --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit
